/**
 * Avis vérifiés Doctoranytime, recopiés tels quels (seules quelques fautes de
 * frappe et d'accents corrigées ; initiales anonymisées par Doctoranytime). Pour ajouter ou retirer un avis,
 * modifiez simplement ce tableau.
 */
export const testimonials = [
  { quote: "Probablement l’une de mes meilleures expériences chez un ostéopathe. Résultat ressenti immédiatement : beaucoup plus de mobilité et de souplesse. Je recommande à 100%.", author: "A. A.", date: "Août 2026" },
  { quote: "Ostéopathe à l’écoute, trouvant la solution la plus adéquate pour soulager votre douleur et recommandant des solutions postérieures pour votre suivi. Je recommande à 100%.", author: "V. S.", date: "Août 2026" },
  { quote: "Rendez-vous en urgence trouvé rapidement. Efficacité et cordialité habituelles.", author: "O. R.", date: "Août 2026" },
  { quote: "Extremely kind, helpful and obviously skilled professional. Would recommend 100%.", author: "I. O.", date: "Juillet 2026" },
  { quote: "La consultation s'est très bien déroulée, j'ai été très satisfait du professionnalisme (diagnostic, explications et traitement). Très bonne expérience à conseiller sans hésiter.", author: "R. Z.", date: "Juin 2026" },
  { quote: "Excellente consultation !", author: "H. A.", date: "Juin 2026" },
  { quote: "Helpful, nice and effective. I feel much better. Thanks.", author: "A. I.", date: "Avril 2026" },
  { quote: "Très bon ostéopathe, à l’écoute et efficace.", author: "É. A.", date: "Avril 2026" },
  { quote: "Highly recommendable.", author: "I. E.", date: "Avril 2026" },
  { quote: "Très bonne prise en main.", author: "A. A.", date: "Avril 2026" },
  { quote: "Très bonne attention.", author: "I. E.", date: "Avril 2026" },
  { quote: "Reçu en urgence, très compétent.", author: "A. E.", date: "Mars 2026" },
  { quote: "Le mec maîtrise son métier à la perfection. Je suis sorti du cabinet avec beaucoup moins de douleur au dos et aux adducteurs. Satisfait à 200%, je recommande fortement.", author: "A. D.", date: "Mars 2026" },
  { quote: "Ostéopathe compétent.", author: "U. I.", date: "Mars 2026" },
  { quote: "Séance très efficace : à l'écoute, il a pu circonscrire le problème et agir de manière adaptée et concluante, je le recommande !", author: "A. H.", date: "Janvier 2026" },
  { quote: "Très professionnel et cordial.", author: "M. A.", date: "Décembre 2025" },
  { quote: "Très professionnel, il m'a été d'un grand secours. En une visite mon problème est quasi réglé. Je recommande vivement.", author: "I. I.", date: "Septembre 2025" },
  { quote: "Praticien doux et efficace. Prend le temps gentiment.", author: "A. A.", date: "Août 2025" },
  { quote: "Séance tout à fait en ligne avec attentes.", author: "E. A.", date: "Août 2025" },
  { quote: "Monsieur Otu est très consciencieux, il a pris le temps nécessaire pour analyser mon problème.", author: "E. E.", date: "Juin 2025" },
  { quote: "Top, merci à David, cela fait bien de ne plus sentir les douleurs. Très à l’écoute et de bon conseil.", author: "I. O.", date: "Juin 2025" },
  { quote: "Excellent ostéopathe, à l’écoute et très professionnel. Il m’a soulagé d’un problème au genou persistant dès les premières séances. Ses explications sont claires et ses gestes précis. Je recommande vivement !", author: "É. D.", date: "Mai 2025" },
  { quote: "Je suis venu pour une consultation générale, il est à l’écoute et donne de bons conseils. Je lui ai parlé également de mes douleurs au genou, il m’a donné quelques mouvements à faire au quotidien. Je recommande !", author: "R. L.", date: "Mai 2025" },
  { quote: "Gentle in his movements, listens attentively and patiently to my descriptions of my issues, is understanding, friendly, explains well when I ask him any questions, and is clear in his instructions when giving me exercises to do at home.", author: "U. I.", date: "Mai 2025" },
  { quote: "Très bonne écoute de la situation, exploration minutieuse de l'ensemble de la situation corporelle, ambiance très calme et rassurante, action(s) bien ciblée(s)…", author: "H. U.", date: "Mai 2025" },
  { quote: "Monsieur Otu est très professionnel et à l’écoute. Après avoir consulté chez de nombreux professionnels, j’ai enfin trouvé quelqu’un qui a pris la peine de comprendre mon besoin et mon problème avant de me manipuler. Je recommande !", author: "O. A.", date: "Mai 2025" },
  { quote: "Praticien très compétent. Il explique le problème et comment il va procéder.", author: "S. E.", date: "Avril 2025" },
  { quote: "Professionnel et à l'écoute. Je venais pour un problème de dos qui se répercutait sur ma poitrine, les douleurs ont disparu et je sens plus de mobilité au niveau de mon dos maintenant.", author: "R. H.", date: "Avril 2025" },
  { quote: "Brilliant guy!", author: "I. Y.", date: "Avril 2025" },
] as const;
